name: tann-dev
channels:
  - conda-forge
  - defaults
  - titan-search
dependencies:
  - gcc =8.5 # [linux]
  - gxx =8.5 # [linux]
  - sysroot_linux-64=2.17 # [linux]
  - turbo
  - gtest
  - boost
  - libaio
  - gmock
  - mkl-devel  # [x86_64]